creation_rules:
  - age:
      # hosts
      - age1tag1q0vhe8lc9gy4tt2sn3x9l22w0h7f0epeqcznr6jlznuvjd9d769rx7usehz # azalea
      - age1tag1qgxdvvdesyskn6zlvey0de6xfh8k6dqpmwav8p0kz0wc0wk47d5qjt5zu8e # carbon
      - age17ln4ecr7u9n48y6hddhw6qq9apd8c8zxhwvnhx0lty52uzspdv9qrfs3ma # nephele
      - age1tag1qgxtea2w2rartg7xjtjwxj5z0dscz882ls9k6szul8gy8knupzx7vhgnh8t # sunflower
      # yubikeys
      - age1yubikey1qvag83hwxux6agjr3zj6gn4083j8kr8pucml7l92tz7rnchtzd6hv6l9us6 # 35203939, Slot: 1
      - age1yubikey1q26z4s8dkaefe0t02ry5986x20nftcqe6g4ngkuhnx4tresztnvewc47j0u # 27419328, Slot: 1
      - age1yubikey1q0j42dwq5dr3x7vl6hq3g3lkzr9wgp76anrs65rt3gj4nhk6dlyhgu3dscx # 25905600, Slot: 1
      - age1yubikey1qvlz7d7gfx7uaurs5jyfjd3uf9ppvk6j0ksqc3rfmverzr7dv5vygnxq8jp # 27783866, Slot: 1
      - age1yubikey1qwlgsvduej6fdzhew5synrm92g90u6rtzjg824rjzj77mx0hf3ys758lcvr # 27783800, Slot: 1

